package stats

// AUTO-GENERATED FILE - DO NOT EDIT
// USE THE SCRIPT parse_units_ruleset.js TO RE-GENERATE IF NEEDED

import (
	"freecocoa/src/models"
)

// UnitClassStats lists all unit classes and combat-relevant flags as extracted
// from units.ruleset.
var UnitClassStats = map[string]models.UnitClass{
	"missile": {
		NameEnum:    models.Missile,
		Missile:     true,
		Unreachable: true,
	},
	"land": {
		NameEnum:       models.Land,
		TerrainDefense: true,
		CanFortify:     true,
	},
	"smallland": {
		NameEnum:       models.SmallLand,
		TerrainDefense: true,
		CanFortify:     true,
	},
	"bigland": {
		NameEnum:   models.BigLand,
		CanFortify: true,
	},
	"bigsiege": {
		NameEnum:        models.BigSiege,
		CanFortify:      true,
		AttackNonNative: true,
	},
	"merchant": {
		NameEnum:       models.Merchant,
		TerrainDefense: true,
	},
	"sea": {
		NameEnum:        models.Sea,
		AttackNonNative: true,
	},
	"trireme": {
		NameEnum: models.Trireme,
	},
	"helicopter": {
		NameEnum:    models.Helicopter,
		Unreachable: true,
	},
	"air": {
		NameEnum:    models.Air,
		Unreachable: true,
	},
}

// UnitStats lists all units combat stats and combat-relevant flags as extracted
// from units.ruleset.
var UnitStats = map[string]models.UnitDetails{
	"settlers": {
		Name:    "Settlers",
		Class:   UnitClassStats["smallland"],
		Attack:  0,
		Defense: 1,
		HP:      20,
		FP:      1,
	},
	"migrants": {
		Name:    "Migrants",
		Class:   UnitClassStats["smallland"],
		Attack:  0,
		Defense: 1,
		HP:      20,
		FP:      1,
	},
	"immigrants": {
		Name:    "Immigrants",
		Class:   UnitClassStats["smallland"],
		Attack:  0,
		Defense: 1,
		HP:      20,
		FP:      1,
	},
	"tribal_worker": {
		Name:    "Tribal Workers",
		Class:   UnitClassStats["smallland"],
		Attack:  0,
		Defense: 1,
		HP:      10,
		FP:      1,
	},
	"worker": {
		Name:    "Workers",
		Class:   UnitClassStats["smallland"],
		Attack:  0,
		Defense: 1,
		HP:      10,
		FP:      1,
	},
	"engineers": {
		Name:    "Engineers",
		Class:   UnitClassStats["smallland"],
		Attack:  0,
		Defense: 2,
		HP:      20,
		FP:      1,
	},
	"warriors": {
		Name:    "Warriors",
		Class:   UnitClassStats["land"],
		Attack:  1,
		Defense: 1,
		HP:      10,
		FP:      1,
	},
	"phalanx": {
		Name:    "Phalanx",
		Class:   UnitClassStats["land"],
		Attack:  1,
		Defense: 2,
		HP:      10,
		FP:      1,
	},
	"archers": {
		Name:    "Archers",
		Class:   UnitClassStats["land"],
		Attack:  3,
		Defense: 1,
		HP:      10,
		FP:      1,
	},
	"legion": {
		Name:    "Swordsmen",
		Class:   UnitClassStats["land"],
		Attack:  4,
		Defense: 2,
		HP:      10,
		FP:      1,
	},
	"pikemen": {
		Name:    "Pikemen",
		Class:   UnitClassStats["land"],
		Attack:  2,
		Defense: 3,
		HP:      10,
		FP:      1,
	},
	"musketeers": {
		Name:    "Musketeers",
		Class:   UnitClassStats["land"],
		Attack:  3,
		Defense: 3,
		HP:      20,
		FP:      1,
	},
	"riflemen": {
		Name:    "Riflemen",
		Class:   UnitClassStats["land"],
		Attack:  5,
		Defense: 4,
		HP:      20,
		FP:      1,
	},
	"infantry": {
		Name:    "Infantry",
		Class:   UnitClassStats["land"],
		Attack:  5,
		Defense: 6,
		HP:      20,
		FP:      1,
	},
	"alpine_troops": {
		Name:    "Alpine Troops",
		Class:   UnitClassStats["land"],
		Attack:  7,
		Defense: 4,
		HP:      20,
		FP:      1,
	},
	"partisan": {
		Name:    "Partisan",
		Class:   UnitClassStats["land"],
		Attack:  4,
		Defense: 5,
		HP:      20,
		FP:      1,
	},
	"fanatics": {
		Name:    "Fanatics",
		Class:   UnitClassStats["land"],
		Attack:  3,
		Defense: 4,
		HP:      20,
		FP:      1,
	},
	"marines": {
		Name:    "Marines",
		Class:   UnitClassStats["land"],
		Attack:  8,
		Defense: 5,
		HP:      20,
		FP:      1,
	},
	"paratroopers": {
		Name:    "Paratroopers",
		Class:   UnitClassStats["land"],
		Attack:  6,
		Defense: 4,
		HP:      20,
		FP:      1,
	},
	"mech_inf": {
		Name:    "Mech. Inf.",
		Class:   UnitClassStats["bigland"],
		Attack:  6,
		Defense: 6,
		HP:      30,
		FP:      1,
	},
	"horsemen": {
		Name:    "Horsemen",
		Class:   UnitClassStats["land"],
		Attack:  2,
		Defense: 1,
		HP:      10,
		FP:      1,
		Horse:   true,
	},
	"chariot": {
		Name:    "Chariot",
		Class:   UnitClassStats["bigland"],
		Attack:  4,
		Defense: 1,
		HP:      10,
		FP:      1,
		Horse:   true,
	},
	"elephants": {
		Name:    "Elephants",
		Class:   UnitClassStats["land"],
		Attack:  3,
		Defense: 2,
		HP:      10,
		FP:      1,
		Horse:   true,
	},
	"crusaders": {
		Name:    "Crusaders",
		Class:   UnitClassStats["land"],
		Attack:  3,
		Defense: 2,
		HP:      15,
		FP:      1,
		Horse:   true,
	},
	"knights": {
		Name:    "Knights",
		Class:   UnitClassStats["land"],
		Attack:  6,
		Defense: 3,
		HP:      10,
		FP:      1,
		Horse:   true,
	},
	"dragoons": {
		Name:    "Dragoons",
		Class:   UnitClassStats["land"],
		Attack:  5,
		Defense: 2,
		HP:      20,
		FP:      1,
		Horse:   true,
	},
	"cavalry": {
		Name:    "Cavalry",
		Class:   UnitClassStats["land"],
		Attack:  8,
		Defense: 3,
		HP:      20,
		FP:      1,
		Horse:   true,
	},
	"armor": {
		Name:    "Armor",
		Class:   UnitClassStats["bigland"],
		Attack:  10,
		Defense: 5,
		HP:      30,
		FP:      1,
	},
	"catapult": {
		Name:       "Catapult",
		Class:      UnitClassStats["bigsiege"],
		Attack:     5,
		Defense:    1,
		HP:         10,
		FP:         1,
		CityBuster: true,
	},
	"cannon": {
		Name:       "Cannon",
		Class:      UnitClassStats["bigsiege"],
		Attack:     8,
		Defense:    1,
		HP:         20,
		FP:         1,
		CityBuster: true,
	},
	"artillery": {
		Name:       "Artillery",
		Class:      UnitClassStats["bigsiege"],
		Attack:     10,
		Defense:    2,
		HP:         20,
		FP:         1,
		CityBuster: true,
	},
	"howitzer": {
		Name:       "Howitzer",
		Class:      UnitClassStats["bigsiege"],
		Attack:     12,
		Defense:    2,
		HP:         30,
		FP:         1,
		CityBuster: true,
	},
	"fighter": {
		Name:        "Fighter",
		Class:       UnitClassStats["air"],
		Attack:      4,
		Defense:     4,
		HP:          20,
		FP:          1,
		AirAttacker: true,
	},
	"bomber": {
		Name:        "Bomber",
		Class:       UnitClassStats["air"],
		Attack:      6,
		Defense:     1,
		HP:          30,
		FP:          1,
		AirAttacker: true,
	},
	"helicopter": {
		Name:        "Helicopter",
		Class:       UnitClassStats["helicopter"],
		Attack:      5,
		Defense:     3,
		HP:          30,
		FP:          1,
		AirAttacker: true,
	},
	"stealth_fighter": {
		Name:        "Stealth Fighter",
		Class:       UnitClassStats["air"],
		Attack:      8,
		Defense:     7,
		HP:          20,
		FP:          1,
		AirAttacker: true,
	},
	"stealth_bomber": {
		Name:        "Stealth Bomber",
		Class:       UnitClassStats["air"],
		Attack:      9,
		Defense:     3,
		HP:          30,
		FP:          1,
		AirAttacker: true,
	},
	"trireme": {
		Name:            "Trireme",
		Class:           UnitClassStats["trireme"],
		Attack:          1,
		Defense:         1,
		HP:              10,
		FP:              1,
		BadCityDefender: true,
	},
	"barge": {
		Name:            "Barge",
		Class:           UnitClassStats["trireme"],
		Attack:          0,
		Defense:         2,
		HP:              20,
		FP:              1,
		BadCityDefender: true,
	},
	"longboat": {
		Name:            "Longboat",
		Class:           UnitClassStats["sea"],
		Attack:          1,
		Defense:         2,
		HP:              4,
		FP:              1,
		BadCityDefender: true,
	},
	"square_rigged_caravel": {
		Class:           UnitClassStats["sea"],
		Attack:          3,
		Defense:         2,
		HP:              8,
		FP:              1,
		BadCityDefender: true,
	},
	"caravel": {
		Name:            "Caravel",
		Class:           UnitClassStats["sea"],
		Attack:          1,
		Defense:         2,
		HP:              10,
		FP:              1,
		BadCityDefender: true,
	},
	"galleon": {
		Name:            "Galleon",
		Class:           UnitClassStats["sea"],
		Attack:          0,
		Defense:         2,
		HP:              20,
		FP:              1,
		BadCityDefender: true,
	},
	"frigate": {
		Name:            "Frigate",
		Class:           UnitClassStats["sea"],
		Attack:          4,
		Defense:         3,
		HP:              20,
		FP:              1,
		BadCityDefender: true,
	},
	"flagship_frigate": {
		Name:            "Flagship Frigate",
		Class:           UnitClassStats["sea"],
		Attack:          5,
		Defense:         3,
		HP:              22,
		FP:              1,
		BadCityDefender: true,
	},
	"ironclad": {
		Name:            "Ironclad",
		Class:           UnitClassStats["sea"],
		Attack:          5,
		Defense:         6,
		HP:              20,
		FP:              1,
		BadCityDefender: true,
	},
	"destroyer": {
		Name:            "Destroyer",
		Class:           UnitClassStats["sea"],
		Attack:          4,
		Defense:         4,
		HP:              30,
		FP:              1,
		BadCityDefender: true,
	},
	"cruiser": {
		Name:            "Cruiser",
		Class:           UnitClassStats["sea"],
		Attack:          4,
		Defense:         8,
		HP:              30,
		FP:              1,
		BadCityDefender: true,
	},
	"aegis_cruiser": {
		Name:            "AEGIS Cruiser",
		Class:           UnitClassStats["sea"],
		Attack:          8,
		Defense:         8,
		HP:              30,
		FP:              1,
		BadCityDefender: true,
	},
	"battleship": {
		Name:            "Battleship",
		Class:           UnitClassStats["sea"],
		Attack:          14,
		Defense:         14,
		HP:              30,
		FP:              2,
		BadCityDefender: true,
	},
	"submarine": {
		Name:            "Submarine",
		Class:           UnitClassStats["sea"],
		Attack:          12,
		Defense:         4,
		HP:              20,
		FP:              1,
		Submarine:       true,
		BadCityDefender: true,
	},
	"nuclear_submarine": {
		Name:            "Nuclear Submarine",
		Class:           UnitClassStats["sea"],
		Attack:          12,
		Defense:         4,
		HP:              20,
		FP:              1,
		Submarine:       true,
		BadCityDefender: true,
	},
	"carrier": {
		Name:            "Carrier",
		Class:           UnitClassStats["sea"],
		Attack:          0,
		Defense:         10,
		HP:              40,
		FP:              1,
		BadCityDefender: true,
	},
	"transport": {
		Name:            "Transport",
		Class:           UnitClassStats["sea"],
		Attack:          0,
		Defense:         3,
		HP:              30,
		FP:              1,
		BadCityDefender: true,
	},
	"missile": {
		Name:        "Missile",
		Class:       UnitClassStats["missile"],
		Attack:      15,
		Defense:     0,
		HP:          2,
		FP:          2,
		AirAttacker: true,
	},
	"cruise_missile": {
		Name:        "Cruise Missile",
		Class:       UnitClassStats["missile"],
		Attack:      10,
		Defense:     0,
		HP:          5,
		FP:          3,
		CityBuster:  true,
		AirAttacker: true,
	},
	"intercontinental_missile": {
		Name:        "Intercontinental Missile",
		Class:       UnitClassStats["missile"],
		Attack:      25,
		Defense:     0,
		HP:          5,
		FP:          3,
		AirAttacker: true,
	},
	"nuclear_bomb": {
		Name:    "Nuclear Bomb",
		Class:   UnitClassStats["missile"],
		Attack:  99,
		Defense: 0,
		HP:      10,
		FP:      1,
	},
	"nuclear": {
		Name:        "Nuclear",
		Class:       UnitClassStats["missile"],
		Attack:      99,
		Defense:     0,
		HP:          10,
		FP:          1,
		AirAttacker: true,
	},
	"diplomat": {
		Name:    "Diplomat",
		Class:   UnitClassStats["smallland"],
		Attack:  0,
		Defense: 0,
		HP:      10,
		FP:      1,
	},
	"spy": {
		Name:    "Spy",
		Class:   UnitClassStats["smallland"],
		Attack:  0,
		Defense: 0,
		HP:      10,
		FP:      1,
	},
	"operative": {
		Name:    "Operative",
		Class:   UnitClassStats["smallland"],
		Attack:  0,
		Defense: 0,
		HP:      10,
		FP:      1,
	},
	"scribe": {
		Name:    "Scribe",
		Class:   UnitClassStats["smallland"],
		Attack:  0,
		Defense: 0,
		HP:      10,
		FP:      1,
	},
	"scholar": {
		Name:    "Scholar",
		Class:   UnitClassStats["smallland"],
		Attack:  0,
		Defense: 0,
		HP:      10,
		FP:      1,
	},
	"caravan": {
		Name:    "Caravan",
		Class:   UnitClassStats["merchant"],
		Attack:  0,
		Defense: 1,
		HP:      10,
		FP:      1,
	},
	"freight": {
		Name:    "Freight",
		Class:   UnitClassStats["merchant"],
		Attack:  0,
		Defense: 2,
		HP:      20,
		FP:      1,
	},
	"explorer": {
		Name:    "Explorer",
		Class:   UnitClassStats["smallland"],
		Attack:  0,
		Defense: 1,
		HP:      7,
		FP:      1,
	},
	"leader": {
		Name:    "Leader",
		Class:   UnitClassStats["land"],
		Attack:  0,
		Defense: 2,
		HP:      20,
		FP:      1,
	},
	"barbarian_leader": {
		Name:    "Barbarian Leader",
		Class:   UnitClassStats["land"],
		Attack:  0,
		Defense: 0,
		HP:      10,
		FP:      1,
	},
	"awacs": {
		Name:    "AWACS",
		Class:   UnitClassStats["air"],
		Attack:  0,
		Defense: 1,
		HP:      20,
		FP:      1,
	},
	"fusion_fighter": {
		Name:        "Fusion Fighter",
		Class:       UnitClassStats["air"],
		Attack:      8,
		Defense:     7,
		HP:          20,
		FP:          1,
		AirAttacker: true,
	},
	"fusion_bomber": {
		Name:        "Fusion Bomber",
		Class:       UnitClassStats["air"],
		Attack:      9,
		Defense:     3,
		HP:          30,
		FP:          1,
		AirAttacker: true,
	},
	"fusion_battleship": {
		Name:            "Fusion Battleship",
		Class:           UnitClassStats["sea"],
		Attack:          24,
		Defense:         12,
		HP:              30,
		FP:              3,
		BadCityDefender: true,
	},
	"fusion_armor": {
		Name:    "Fusion Armor",
		Class:   UnitClassStats["bigland"],
		Attack:  10,
		Defense: 5,
		HP:      30,
		FP:      2,
	},
	"cargo_aircraft": {
		Name:    "Cargo Aircraft",
		Class:   UnitClassStats["air"],
		Attack:  0,
		Defense: 3,
		HP:      30,
		FP:      1,
	},
}
